### PR TITLE
Switch to multiversioned kernel packages

### PR DESCRIPTION
**Pull request by Conan-Kudo**
DNF supports multiple versions of the same package name
being installed as long as there are no file conflicts, and
handles responsibly cleaning up old kernels automatically
when this functionality is used properly.

Since we are exclusively using DNF for package management,
we should use this functionality so that kernels are more
manageable on systems.

### CODE REVIEW

**Comment by berolinux** [comment]
Looks good to me except I don't see anything obsoleting the -latest package and older kernel packages... Just not sure we should be doing that this late...

**Comment by Conan-Kudo** [comment]
@berolinux The `-latest` packages are being obsoleted by the multiversioned packages, and I'm not sure there's a good way to obsolete the old packages that have the kernel version in the name.

I think we should make this change now because that will allow use to leverage the features specific to kernel packages in DNF and make things easier in the future.

**Comment by benbullard79** [comment]
I'm hoping that this can be done so that users are left with not just the new kernel but the most recently installed previous kernel so user has a backup if new kernel does not work for them.

As I recall this is something we talked about and more or less agreed on in the past.

**Comment by Conan-Kudo** [comment]
@benbullard79 Multiversioned packages (or "install-only packages" as they used to known as) have a flag in DNF controlling how many will be kept around at a time: https://dnf.readthedocs.io/en/latest/conf_ref.html#installonlypkgs-label

Currently DNF will keep around three at a time of any multiversioned package series. This can be reduced or increased at the user's desire in `/etc/dnf/dnf.conf` by changing the `installonly_limit`.

**Pull request merged**
